// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using infra;

#nullable disable

namespace infra.Migrations
{
    [DbContext(typeof(ContextBase))]
    [Migration("20231208212310_atualizacao")]
    partial class atualizacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("entidades.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("BudgetMaximo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoBeneficios")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FoneSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HorarioTrabalho")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LocalContratacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModeloContratacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrioridadeContratacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RegimeTrabalho")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequisitosComportamentais")
                        .HasColumnType("longtext");

                    b.Property<string>("RequisitosTecnicos")
                        .HasColumnType("longtext");

                    b.Property<string>("Responsabilidades")
                        .HasColumnType("longtext");

                    b.Property<string>("Senioridade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoContratacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Vaga");
                });
#pragma warning restore 612, 618
        }
    }
}
